Feature #21 log get
miraikeitai2020/backend-log pull request #31
Opened 2020-11-01 12:06 UTC by kondo1018008

### issue
------------------
#21 #22 #23 #24 
### 内容
------------------
ヘッダーの"x-token"にlog_idをGETリクエストで投げると，レスポンスでlog情報が返ってくる

### 確認方法
------------------

`docker-compose up -d`
でデータベースコンテナを起動
cmdで
`go run main.go`を実行
http://localhost:8080/api/log にGETメソッドで
header
`x-token: "log_id"`
を投げて
`{
    "Date": "2017-02-01T03:15:45Z",
    "WorkTime": 810,
    "Concentration": [
        11.4,
        51.4,
        191.9,
        81
    ],
    "LogName": "サービス残業"
}`
のようにresponseが返ってきたら問題なし

2020-11-01 18:00 UTC, SaKu2110 requested changes

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/handler/handler.go
> +			c.String(http.StatusBadRequest, "Request is failed: "+err.Error())
↓みたいなレスポンスを返されると，クライアントがエラーハンドリングする際に死ぬからおすすめしない
```
"Please enter x-token"
```

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/handler/handler.go
> +			c.String(http.StatusBadRequest, "Request is failed: "+err.Error())
↓みたいな構造体を返すとクライアントが幸せになれる
```go
type Errors struct {
  Code        int    `json:"code"`
  Messsage    string `json:"message"`
  Description string `json:"description"`
}

type HogeResponse struct {
  token string `json:"token"`
  err   Errors `json:"error"`
}
```

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/handler/handler.go
> +		if Log.LogID == "" {
`Log := model.Log{}`って
line: 61 `Logs, err := Log.FindByLogID()`でしか使わないから正直いる？ってなってる
あと，line: 51はこれでいいと思う↓
```go
if c.Request.Header.Get("x-token") == "" {
}
```

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/handler/handler.go
> +			c.String(http.StatusInternalServerError, err.Error())
ここのエラーハンドリングも上と同様ね

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/handler/handler.go
> +			c.String(http.StatusBadRequest, "Request is failed: "+err.Error())
line 68でJSONで返してるのにエラーハンドリングはstringはどういう意図？

2020-11-01 18:00 UTC, SaKu2110 commented on pkg/server/model/model.go
> +	log.UserID = utils.CreateHashString(l.UserID)
```go
l.UserID = = utils.CreateHashString(l.UserID)
```
でよくない？（このあと使わんし...）

2020-11-01 20:46 UTC, kondo1018008 commented on pkg/server/model/model.go
> +	log.UserID = utils.CreateHashString(l.UserID)
レシーバの構造体の変数に変更を加えたくないので別の構造体を定義してデータベースに保存してる

2020-11-01 20:48 UTC, kondo1018008 commented on pkg/server/handler/handler.go
> +		if Log.LogID == "" {
x-tokenは普通に別のところでも使いたいので，stringの変数で受け取ることにして`Log := model.Log{}`は消した

2020-11-01 20:53 UTC, kondo1018008 commented on pkg/server/handler/handler.go
> +			c.String(http.StatusBadRequest, "Request is failed: "+err.Error())
stringでエラー返すのは確かにおかしいからエラーはJSONで返すことにした
元のレスポンスにエラーを含ませるのは設計書書き直さなきゃいけないので，エラーのJSONとレスポンスのJSONは分けてる

2020-11-02 14:56 UTC, SaKu2110 approved these changes

2020-11-02 14:56 UTC, SaKu2110 commented on pkg/server/view/view.go
> +	c.JSON(200, response)
他の部分は`http.StatusHogeHoge`使ってるからここも`http.StatusOK`使うべき

2020-11-02 15:00 UTC, SaKu2110 commented
![LGTM](https://cdn.lgtmoon.dev/images/105076)

2020-11-02 21:14 UTC, merged